version: '2'

services:

  pushgateway:
    image: prom/pushgateway
    hostname: proc-pushgateway
    ports:
        - "9091:9091"

  mongo-proc:
    image: mongo:latest
    restart: always
    user: mongodb
    hostname: opac-proc-mongo-proc
    ports:
        - 27017
    volumes:
        - /etc/localtime:/etc/localtime:ro

  mongo-logs:
    image: mongo:latest
    restart: always
    user: mongodb
    hostname: opac-proc-mongo-logs
    ports:
        - 27017
    volumes:
        - /etc/localtime:/etc/localtime:ro

  redis:
    image: redis:alpine
    user: redis
    restart: always
    hostname: opac-proc-redis
    ports:
        - "6379:6379"  # deve ser o mesmo que a env var: OPAC_PROC_REDIS_PORT
    volumes:
      - redis-data-dev:/data
      - /etc/localtime:/etc/localtime:ro

  rq-worker:
    images: scieloorg/opac_proc
    command: /start_worker.sh
    user: nobody
    restart: always
    hostname: opac-proc-rqworker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/scielosp_org/htdocs/img/revistas:/app/data/img:ro
      - /mnt/scielosp_org/bases/xml:/app/data/xml:ro
      - /mnt/scielosp_org/bases/pdf:/app/data/pdf:ro
    environment:
      - OPAC_PROC_LOG_LEVEL=DEBUG
      - OPAC_PROC_ARTICLE_META_THRIFT_DOMAIN=articlemeta.scielo.org
      - OPAC_PROC_ARTICLE_META_THRIFT_PORT=11621
      - OPAC_PROC_COLLECTION=spa
      - OPAC_PROC_DEBUG=True
      - OPAC_PROC_TESTING=False
      - OPAC_PROC_SECRET_KEY="s3cr3t-k3y"
      # - OPAC_PROC_SENTRY_DSN=
      # mongo processamento
      - OPAC_PROC_MONGODB_NAME=opac_proc
      - OPAC_PROC_MONGODB_HOST=mongo-proc
      - OPAC_PROC_MONGODB_PORT=27017
      # - OPAC_PROC_MONGODB_USER=
      # - OPAC_PROC_MONGODB_PASS=
      # mongo db do opac
      - OPAC_MONGODB_NAME=${OPAC_MONGODB_NAME}  # nome do banco mongo do OPAC
      - OPAC_MONGODB_HOST=${OPAC_MONGODB_HOST}  # host do banco mongo do OPAC
      - OPAC_MONGODB_PORT=${OPAC_MONGODB_PORT}  # porta do banco mongo do OPAC
      # - OPAC_MONGODB_USER=
      # - OPAC_MONGODB_PASS=
      # mongo logs do opac
      - OPAC_PROC_LOG_MONGODB_NAME=opac_proc_logs
      - OPAC_PROC_LOG_MONGODB_HOST=mongo-logs
      - OPAC_PROC_LOG_MONGODB_PORT=27017
      # - OPAC_PROC_LOG_MONGODB_USER=
      # - OPAC_PROC_LOG_MONGODB_PASS=
      # Redis:
      - OPAC_PROC_REDIS_HOST=redis
      - OPAC_PROC_REDIS_PORT=6379

      # Opac_ssm_server
      - OPAC_SSM_GRPC_SERVER_HOST=homolog.grpc.ssm.scielo.org
      - OPAC_SSM_GRPC_SERVER_PORT=8005
      # Opac_ssm_api
      - OPAC_SSM_PROTO_FILE_HOST=raw.githubusercontent.com
      - OPAC_SSM_PROTO_FILE_PORT=80
      - OPAC_SSM_PROTO_FILE_PATH=/scieloorg/opac_ssm/master/grpc_ssm/opac.proto
      # Email
      - OPAC_PROC_WEB_REGISTRATION_ENABLED='True'
      - OPAC_PROC_ACCOUNTS_REQUIRES_EMAIL_CONFIRMATION='True'
      - OPAC_PROC_DEFAULT_EMAIL=scielo@scielo.org
      - OPAC_PROC_MAIL_SERVER=localhost
      - OPAC_PROC_MAIL_PORT='1025'
      - OPAC_PROC_MAIL_USE_TLS='False'
      - OPAC_PROC_MAIL_USE_SSL='False'
      - OPAC_PROC_MAIL_USERNAME=None
      - OPAC_PROC_MAIL_PASSWORD=None
      # Static HTML Generator
      - OPAC_PROC_ARTICLE_CSS_URL=http://ssm.scielo.org/media/assets/css/scielo-article.css
      - OPAC_PROC_ARTICLE_PRINT_CSS_URL=http://ssm.scielo.org/media/assets/css/scielo-print.css
      - OPAC_PROC_ARTICLE_JS_URL=http://ssm.scielo.org/media/assets/js/scielo-article.js
      # Assets
      - OPAC_PROC_ASSETS_RAISE_ERROR=False
      # Prometheus
      - OPAC_PROMETHEUS_ENABLED=True
      - OPAC_PROC_PROMPG_HOST=pushgateway
      - OPAC_PROC_PROMPG_PORT=9091

  rq-scheduler:
    images: scieloorg/opac_proc
    command: /start_scheduler.sh
    user: nobody
    restart: always
    hostname: opac-proc-rqscheduler
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/scielosp_org/htdocs/img/revistas:/app/data/img:ro
      - /mnt/scielosp_org/bases/xml:/app/data/xml:ro
      - /mnt/scielosp_org/bases/pdf:/app/data/pdf:ro
    environment:
      - OPAC_PROC_LOG_LEVEL=DEBUG
      - OPAC_PROC_ARTICLE_META_THRIFT_DOMAIN=articlemeta.scielo.org
      - OPAC_PROC_ARTICLE_META_THRIFT_PORT=11621
      - OPAC_PROC_COLLECTION=spa
      - OPAC_PROC_DEBUG=True
      - OPAC_PROC_TESTING=False
      - OPAC_PROC_SECRET_KEY="s3cr3t-k3y"
      # - OPAC_PROC_SENTRY_DSN=
      # mongo processamento
      - OPAC_PROC_MONGODB_NAME=opac_proc
      - OPAC_PROC_MONGODB_HOST=mongo-proc
      - OPAC_PROC_MONGODB_PORT=27017
      # - OPAC_PROC_MONGODB_USER=
      # - OPAC_PROC_MONGODB_PASS=
      # mongo db do opac
      - OPAC_MONGODB_NAME=${OPAC_MONGODB_NAME}  # nome do banco mongo do OPAC
      - OPAC_MONGODB_HOST=${OPAC_MONGODB_HOST}  # host do banco mongo do OPAC
      - OPAC_MONGODB_PORT=${OPAC_MONGODB_PORT}  # porta do banco mongo do OPAC
      # - OPAC_MONGODB_USER=
      # - OPAC_MONGODB_PASS=
      # mongo logs do opac
      - OPAC_PROC_LOG_MONGODB_NAME=opac_proc_logs
      - OPAC_PROC_LOG_MONGODB_HOST=mongo-logs
      - OPAC_PROC_LOG_MONGODB_PORT=27017
      # - OPAC_PROC_LOG_MONGODB_USER=
      # - OPAC_PROC_LOG_MONGODB_PASS=
      # Redis:
      - OPAC_PROC_REDIS_HOST=redis
      - OPAC_PROC_REDIS_PORT=6379

      # Opac_ssm_server
      - OPAC_SSM_GRPC_SERVER_HOST=homolog.grpc.ssm.scielo.org
      - OPAC_SSM_GRPC_SERVER_PORT=8005
      # Opac_ssm_api
      - OPAC_SSM_PROTO_FILE_HOST=raw.githubusercontent.com
      - OPAC_SSM_PROTO_FILE_PORT=80
      - OPAC_SSM_PROTO_FILE_PATH=/scieloorg/opac_ssm/master/grpc_ssm/opac.proto
      # Email
      - OPAC_PROC_WEB_REGISTRATION_ENABLED='True'
      - OPAC_PROC_ACCOUNTS_REQUIRES_EMAIL_CONFIRMATION='True'
      - OPAC_PROC_DEFAULT_EMAIL=scielo@scielo.org
      - OPAC_PROC_MAIL_SERVER=localhost
      - OPAC_PROC_MAIL_PORT='1025'
      - OPAC_PROC_MAIL_USE_TLS='False'
      - OPAC_PROC_MAIL_USE_SSL='False'
      - OPAC_PROC_MAIL_USERNAME=None
      - OPAC_PROC_MAIL_PASSWORD=None
      # Static HTML Generator
      - OPAC_PROC_ARTICLE_CSS_URL=http://ssm.scielo.org/media/assets/css/scielo-article.css
      - OPAC_PROC_ARTICLE_PRINT_CSS_URL=http://ssm.scielo.org/media/assets/css/scielo-print.css
      - OPAC_PROC_ARTICLE_JS_URL=http://ssm.scielo.org/media/assets/js/scielo-article.js
      # Assets
      - OPAC_PROC_ASSETS_RAISE_ERROR=False
      # Prometheus
      - OPAC_PROMETHEUS_ENABLED=True
      - OPAC_PROC_PROMPG_HOST=pushgateway
      - OPAC_PROC_PROMPG_PORT=9091

  webapp:
    images: scieloorg/opac_proc
    user: nobody
    restart: always
    hostname: opac-proc-webapp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/scielosp_org/htdocs/img/revistas:/app/data/img:ro
      - /mnt/scielosp_org/bases/xml:/app/data/xml:ro
      - /mnt/scielosp_org/bases/pdf:/app/data/pdf:ro
    ports:
      - "9000:8000"
    environment:
      - OPAC_PROC_LOG_LEVEL=DEBUG
      - OPAC_PROC_ARTICLE_META_THRIFT_DOMAIN=articlemeta.scielo.org
      - OPAC_PROC_ARTICLE_META_THRIFT_PORT=11621
      - OPAC_PROC_COLLECTION=spa
      - OPAC_PROC_DEBUG=True
      - OPAC_PROC_TESTING=False
      - OPAC_PROC_SECRET_KEY="s3cr3t-k3y"
      # - OPAC_PROC_SENTRY_DSN=
      # mongo processamento
      - OPAC_PROC_MONGODB_NAME=opac_proc
      - OPAC_PROC_MONGODB_HOST=mongo-proc
      - OPAC_PROC_MONGODB_PORT=27017
      # - OPAC_PROC_MONGODB_USER=
      # - OPAC_PROC_MONGODB_PASS=
      # mongo db do opac
      - OPAC_MONGODB_NAME=${OPAC_MONGODB_NAME}  # nome do banco mongo do OPAC
      - OPAC_MONGODB_HOST=${OPAC_MONGODB_HOST}  # host do banco mongo do OPAC
      - OPAC_MONGODB_PORT=${OPAC_MONGODB_PORT}  # porta do banco mongo do OPAC
      # - OPAC_MONGODB_USER=
      # - OPAC_MONGODB_PASS=
      # mongo logs do opac
      - OPAC_PROC_LOG_MONGODB_NAME=opac_proc_logs
      - OPAC_PROC_LOG_MONGODB_HOST=mongo-logs
      - OPAC_PROC_LOG_MONGODB_PORT=27017
      # - OPAC_PROC_LOG_MONGODB_USER=
      # - OPAC_PROC_LOG_MONGODB_PASS=
      # Redis:
      - OPAC_PROC_REDIS_HOST=redis
      - OPAC_PROC_REDIS_PORT=6379
      # Opac_ssm_server
      - OPAC_SSM_GRPC_SERVER_HOST=homolog.grpc.ssm.scielo.org
      - OPAC_SSM_GRPC_SERVER_PORT=8005
      # Opac_ssm_api
      - OPAC_SSM_PROTO_FILE_HOST=raw.githubusercontent.com
      - OPAC_SSM_PROTO_FILE_PORT=80
      - OPAC_SSM_PROTO_FILE_PATH=/scieloorg/opac_ssm/master/grpc_ssm/opac.proto
      # Email
      - OPAC_PROC_WEB_REGISTRATION_ENABLED=True
      - OPAC_PROC_ACCOUNTS_REQUIRES_EMAIL_CONFIRMATION=True
      - OPAC_PROC_DEFAULT_EMAIL=scielo@scielo.org
      - OPAC_PROC_MAIL_SERVER=localhost
      - OPAC_PROC_MAIL_PORT=1025
      - OPAC_PROC_MAIL_USE_TLS=False
      - OPAC_PROC_MAIL_USE_SSL=False
      - OPAC_PROC_MAIL_USERNAME=None
      - OPAC_PROC_MAIL_PASSWORD=None
      # Static HTML Generator
      - OPAC_PROC_ARTICLE_CSS_URL=http://ssm.scielo.org/media/assets/css/scielo-article.css
      - OPAC_PROC_ARTICLE_PRINT_CSS_URL=http://ssm.scielo.org/media/assets/css/scielo-print.css
      - OPAC_PROC_ARTICLE_JS_URL=http://ssm.scielo.org/media/assets/js/scielo-article.js
      # Assets
      - OPAC_PROC_ASSETS_RAISE_ERROR=False
      # Prometheus
      - OPAC_PROMETHEUS_ENABLED=True
      - OPAC_PROC_PROMPG_HOST=pushgateway
      - OPAC_PROC_PROMPG_PORT=9091
